version: '3'

services:
  ctf-challenge:
    build: .
    ports:
      - "5555:5555"
    restart: always
    security_opt:
      - no-new-privileges:true
    cap_add:
      - NET_RAW
      - NET_ADMIN
    read_only: true
    tmpfs:
      - /tmp
    networks:
      - ctf_network

networks:
  ctf_network:
    driver: bridge